version: '3'

services:

  # Connection microservice
  # web-socket:
  #   build:
  #     context: ./services/webSocket
  #     dockerfile: Dockerfile.development
  #   ports:
  #     - "3000:3000"
  #   command: npm run start:watch # Use the "start:watch" script
  # Database
  mongo-db:
    build:
      context: ./services/database
      dockerfile: Dockerfile.development
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
