name: publish-commons

on:
  push:
    branches:
      - main
    paths:
      - 'commons/**'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.8.1

    - name: Install dependencies in commons directory
      run: |
        cd commons
        npm i

    - name: Run semantic-release in commons directory
      env:
        HOLY_SHEEP_ACCESS_TOKEN: ${{ secrets.HOLY_SHEEP_ACCESS_TOKEN }}
      run: |
        cd commons
        npx semantic-release